apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: argo-workflows-share
  namespace: argo
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: argo-filestore-pv
  resources:
    requests:
      storage: 1Ti