apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: argo-workflows-share
  namespace: argo
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-taiga
  resources:
    requests:
      storage: 500Gi