# config.toml
[ee]
project = "pdg-project-406720"
auth = true

vector_dataset = "/Users/helium/ncsa/pdg/water-timeseries-v2/tests/data/lake_polygons.parquet"

[output]
# base_path = "/Users/helium/ncsa/pdg/water-timeseries-v2/tests/data/output"
base_path = "/Users/helium/ncsa/pdg/water_timeseries_argo_workflow/utils"
format = "nc"

[range]
years = [2022, 2023, 2024]
months = [6, 7, 8, 9]

[defaults]
years = [2024]
months = [7, 8, 9, 10]