name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - 3-near-real-time-run-argo-workflow
  workflow_dispatch:
    inputs:
      tag:
        description: 'Custom image tag (optional)'
        required: false
        type: string